#!/bin/sh

case $1 in
	"b" | "build")
		wasm-pack build
	;;
	"i" | "install")
		cd www && npm install
	;;
	"s" | "serve")
		cd www && npm start
	;;
	"r" | "run")
		$0 build
		$0 serve
	;;
	"w" | "watch")
		cargo watch -w src -w Cargo.toml -s "$0 build"
	;;
	"e" | "everything")
		$0 build
		$0 install
		$0 serve
	;;
	*)
		echo "build [(b)uild | (s)erve | (r)un | (w)atch | (i)nstall | (e)verything ]"
esac

