#!/bin/sh

case $1 in
	"b" | "build")
		cd graph && cargo build
		cd frontend && wasm-pack build
		cd backend && cargo build
		cd frontend/www && npm install
	;;
	"s" | "serve")
		cd frontend/www && npm start
	;;
	"r" | "run")
		$0 build
		$0 install
		$0 serve
	;;
	"w" | "watch")
		case $2 in
			"b" | "backend")
				cd backend
				cargo watch -w ../graph -w src -w Cargo.toml -x "run"
			;;
			"f" | "frontend")
				cd frontend
				cargo watch -w ../graph -w src -w Cargo.toml -s "wasm-pack build"
			;;
			*)
				echo "build watch [(f)rontend | (b)ackedn]"
		esac
	;;
	"d" | "document")
		D_PRIVATE="--document-private-items"
		D_OPEN="--open"
		SECOND="$2"
		VALID=true
		while [ "$2" != "" ]; do
			if [[ ${SECOND:1:1} == "-" ]]; then
				case $2 in
				"--public")
					D_PRIVATE=""
					;;
				"--quiet")
					D_OPEN=""
					;;
				*)
					VALID=false
					;;
				esac
			elif [ ${SECOND:0:1} == "-" ]; then
				for i in $(seq -s " " 1 ${#SECOND}); do
					case ${SECOND:i:1} in
					"p")
						D_PRIVATE=""
						;;
					"q")
						D_OPEN=""
						;;
					"")
						break
						;;
					*)
						VALID=false
						;;
					esac
				done
			else
				VALID=false
				break
			fi
			shift
		done
		if [ "$VALID" = true ]; then
			echo "cargo doc $D_PRIVATE $D_OPEN --workspace"
			cargo doc $D_PRIVATE $D_OPEN --workspace
		else
			echo "build document [-|--] [(p)ublic | (q)uiet]"
		fi
	;;
	*)
		echo "build [(b)uild | (s)erve | (r)un | (w)atch | (d)ocument]"
esac

